/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as GroupsNewRouteImport } from './routes/groups/new'
import { Route as GroupsGroupIdSettleRouteImport } from './routes/groups/$groupId/settle'
import { Route as GroupsGroupIdExpensesNewRouteImport } from './routes/groups/$groupId/expenses/new'
import { Route as GroupsGroupIdExpensesExpenseIdEditRouteImport } from './routes/groups/$groupId/expenses/$expenseId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdSettleRoute = GroupsGroupIdSettleRouteImport.update({
  id: '/settle',
  path: '/settle',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdExpensesNewRoute =
  GroupsGroupIdExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any)
const GroupsGroupIdExpensesExpenseIdEditRoute =
  GroupsGroupIdExpensesExpenseIdEditRouteImport.update({
    id: '/expenses/$expenseId/edit',
    path: '/expenses/$expenseId/edit',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/groups/$groupId/settle': typeof GroupsGroupIdSettleRoute
  '/groups/$groupId/expenses/new': typeof GroupsGroupIdExpensesNewRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/groups/$groupId/settle': typeof GroupsGroupIdSettleRoute
  '/groups/$groupId/expenses/new': typeof GroupsGroupIdExpensesNewRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/groups/$groupId/settle': typeof GroupsGroupIdSettleRoute
  '/groups/$groupId/expenses/new': typeof GroupsGroupIdExpensesNewRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups/$groupId'
    | '/groups/new'
    | '/groups/$groupId/settle'
    | '/groups/$groupId/expenses/new'
    | '/groups/$groupId/expenses/$expenseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups/$groupId'
    | '/groups/new'
    | '/groups/$groupId/settle'
    | '/groups/$groupId/expenses/new'
    | '/groups/$groupId/expenses/$expenseId/edit'
  id:
    | '__root__'
    | '/'
    | '/groups/$groupId'
    | '/groups/new'
    | '/groups/$groupId/settle'
    | '/groups/$groupId/expenses/new'
    | '/groups/$groupId/expenses/$expenseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  GroupsNewRoute: typeof GroupsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/settle': {
      id: '/groups/$groupId/settle'
      path: '/settle'
      fullPath: '/groups/$groupId/settle'
      preLoaderRoute: typeof GroupsGroupIdSettleRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/expenses/new': {
      id: '/groups/$groupId/expenses/new'
      path: '/expenses/new'
      fullPath: '/groups/$groupId/expenses/new'
      preLoaderRoute: typeof GroupsGroupIdExpensesNewRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/expenses/$expenseId/edit': {
      id: '/groups/$groupId/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/groups/$groupId/expenses/$expenseId/edit'
      preLoaderRoute: typeof GroupsGroupIdExpensesExpenseIdEditRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdSettleRoute: typeof GroupsGroupIdSettleRoute
  GroupsGroupIdExpensesNewRoute: typeof GroupsGroupIdExpensesNewRoute
  GroupsGroupIdExpensesExpenseIdEditRoute: typeof GroupsGroupIdExpensesExpenseIdEditRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdSettleRoute: GroupsGroupIdSettleRoute,
  GroupsGroupIdExpensesNewRoute: GroupsGroupIdExpensesNewRoute,
  GroupsGroupIdExpensesExpenseIdEditRoute:
    GroupsGroupIdExpensesExpenseIdEditRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  GroupsNewRoute: GroupsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
