/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as GroupsNewRouteImport } from './routes/groups/new'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdProfileRouteImport } from './routes/groups/$groupId/profile'
import { Route as GroupsGroupIdSettleRouteImport } from './routes/groups/$groupId/settle'
import { Route as GroupsGroupIdExpensesNewRouteImport } from './routes/groups/$groupId/expenses/new'
import { Route as GroupsGroupIdMembersMemberIdRouteImport } from './routes/groups/$groupId/members/$memberId'
import { Route as GroupsGroupIdExpensesExpenseIdEditRouteImport } from './routes/groups/$groupId/expenses/$expenseId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdProfileRoute = GroupsGroupIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdSettleRoute = GroupsGroupIdSettleRouteImport.update({
  id: '/settle',
  path: '/settle',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdExpensesNewRoute =
  GroupsGroupIdExpensesNewRouteImport.update({
    id: '/expenses/new',
    path: '/expenses/new',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any)
const GroupsGroupIdMembersMemberIdRoute =
  GroupsGroupIdMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any)
const GroupsGroupIdExpensesExpenseIdEditRoute =
  GroupsGroupIdExpensesExpenseIdEditRouteImport.update({
    id: '/expenses/$expenseId/edit',
    path: '/expenses/$expenseId/edit',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/join/$code': typeof JoinCodeRoute
  '/groups/$groupId/profile': typeof GroupsGroupIdProfileRoute
  '/groups/$groupId/settle': typeof GroupsGroupIdSettleRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof GroupsGroupIdExpensesNewRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/groups/new': typeof GroupsNewRoute
  '/join/$code': typeof JoinCodeRoute
  '/groups/$groupId/profile': typeof GroupsGroupIdProfileRoute
  '/groups/$groupId/settle': typeof GroupsGroupIdSettleRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof GroupsGroupIdExpensesNewRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/join/$code': typeof JoinCodeRoute
  '/groups/$groupId/profile': typeof GroupsGroupIdProfileRoute
  '/groups/$groupId/settle': typeof GroupsGroupIdSettleRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/expenses/new': typeof GroupsGroupIdExpensesNewRoute
  '/groups/$groupId/members/$memberId': typeof GroupsGroupIdMembersMemberIdRoute
  '/groups/$groupId/expenses/$expenseId/edit': typeof GroupsGroupIdExpensesExpenseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/groups/$groupId'
    | '/groups/new'
    | '/join/$code'
    | '/groups/$groupId/profile'
    | '/groups/$groupId/settle'
    | '/groups/$groupId/'
    | '/groups/$groupId/expenses/new'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/expenses/$expenseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/groups/new'
    | '/join/$code'
    | '/groups/$groupId/profile'
    | '/groups/$groupId/settle'
    | '/groups/$groupId'
    | '/groups/$groupId/expenses/new'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/expenses/$expenseId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/groups/$groupId'
    | '/groups/new'
    | '/join/$code'
    | '/groups/$groupId/profile'
    | '/groups/$groupId/settle'
    | '/groups/$groupId/'
    | '/groups/$groupId/expenses/new'
    | '/groups/$groupId/members/$memberId'
    | '/groups/$groupId/expenses/$expenseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  GroupsNewRoute: typeof GroupsNewRoute
  JoinCodeRoute: typeof JoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/profile': {
      id: '/groups/$groupId/profile'
      path: '/profile'
      fullPath: '/groups/$groupId/profile'
      preLoaderRoute: typeof GroupsGroupIdProfileRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/settle': {
      id: '/groups/$groupId/settle'
      path: '/settle'
      fullPath: '/groups/$groupId/settle'
      preLoaderRoute: typeof GroupsGroupIdSettleRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/expenses/new': {
      id: '/groups/$groupId/expenses/new'
      path: '/expenses/new'
      fullPath: '/groups/$groupId/expenses/new'
      preLoaderRoute: typeof GroupsGroupIdExpensesNewRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/members/$memberId': {
      id: '/groups/$groupId/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/groups/$groupId/members/$memberId'
      preLoaderRoute: typeof GroupsGroupIdMembersMemberIdRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/expenses/$expenseId/edit': {
      id: '/groups/$groupId/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/groups/$groupId/expenses/$expenseId/edit'
      preLoaderRoute: typeof GroupsGroupIdExpensesExpenseIdEditRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdProfileRoute: typeof GroupsGroupIdProfileRoute
  GroupsGroupIdSettleRoute: typeof GroupsGroupIdSettleRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  GroupsGroupIdExpensesNewRoute: typeof GroupsGroupIdExpensesNewRoute
  GroupsGroupIdMembersMemberIdRoute: typeof GroupsGroupIdMembersMemberIdRoute
  GroupsGroupIdExpensesExpenseIdEditRoute: typeof GroupsGroupIdExpensesExpenseIdEditRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdProfileRoute: GroupsGroupIdProfileRoute,
  GroupsGroupIdSettleRoute: GroupsGroupIdSettleRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  GroupsGroupIdExpensesNewRoute: GroupsGroupIdExpensesNewRoute,
  GroupsGroupIdMembersMemberIdRoute: GroupsGroupIdMembersMemberIdRoute,
  GroupsGroupIdExpensesExpenseIdEditRoute:
    GroupsGroupIdExpensesExpenseIdEditRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  GroupsNewRoute: GroupsNewRoute,
  JoinCodeRoute: JoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
